### ISSUE TITLE
Artix(OpenRC) Freezing/Crashing whenever compressing bigger files (800KiB~)

### ISSUE THREAD

**Issue by casualdegenerate** [byronknoll/cmix#56]
16GB Memory, 255GiB Swap.
Intel i7-8700 (12) @ 4.600GHz

Issue: Using cmix causes my kwin(window manager) to freeze.

I have thoughts on it being a issue with CPU Usage, but I am new to Linux, so I don't know how to use these cpu limit tools or if that is the cause of the issue. If you recognize these symptoms and can reply back onto how to fix this that'd be nice. I had issues like this with other applications when they'd use up a lot of resources(I have a lot of swap, so i don't see memory being an issue here)

**Comment by byronknoll** [comment]
My guess is that this is due to memory usage. cmix RAM usage grows for larger files, so it makes sense that above 800KiB files you would start to reach the 16GB memory limit. I would not expect CPU usage to cause the window manager to freeze, but it seems possible that swapping memory could cause this behavior.

cmix is likely to be very slow with only 16GB RAM and relying on swap. 32GB is recommended. You can try running linux without a window manager (directly through command line) to see if cmix runs that way on your machine for larger files.

**Comment by casualdegenerate** [comment]
Issue solved, using server with 32MB of RAM for bigger files.
It was a RAM storage issue most likely.

I can confirm this is likely because my swap was slow since it was from HDD. I've used my server which uses the same OS, and has 32MB of RAM and it works just like a charm. Will just use cmix on my server whenever doing bigger files for now while I wait for more RAM. Although, I will later try out using bigger files through just the terminal on my host machine to test if I am able to use cmix on this computer with just around 16MB of RAM, with a bit of swap for extra.
